# Generated by Django 4.1.5 on 2023-01-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recension', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recension',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='film',
            old_name='pub_date',
            new_name='pub_date_film',
        ),
        migrations.RenameField(
            model_name='recension',
            old_name='pud_date',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, upload_to='recension/'),
        ),
    ]
