# Generated by Django 4.1.5 on 2023-01-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recension', '0002_alter_recension_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recension/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='pub_date_film',
            field=models.DateField(blank=True, null=True),
        ),
    ]
