# Generated by Django 4.1.5 on 2023-01-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recension', '0004_film_href_remove_film_genre_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='recension.genre'),
        ),
    ]
